version: "3"
services:
    vue-app:
        image: vue-app
        stdin_open: true
        ports: 
            - "3000:3000"
        networks:
            - party-app
    api-server:
        image: api-server
        ports: 
            - "5000:5000"
        networks:
            - party-app
        depends_on:
            - mongo
    mongo:
        image: mongo:3.6.19-xenial
        ports: 
            - "27017:27017"
        networks:
            - party-app
        volumes: 
            - mongo-data:data/db
networks:
    party-app:
        driver: bridge
volumes: 
    mongo-data:
        driver: local